-- Active: 1736772727356@@127.0.0.1@3306@photo_gallery
CREATE DATABASE photo_gallery;


use photo_gallery;


CREATE Table photos(

id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
image_path VARCHAR (250) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);